### ISSUE TITLE
error in adversarial_autoencoder.py 

### ISSUE THREAD

**Issue by p2004r** [eriklindernoren/Keras-GAN#1]
if` __name__ == '__main__':
        aae = AdversarialAutoencoder()
   

    Layer (type)                 Output Shape              Param #   
    =================================================================
    dense_10 (Dense)             (None, 512)               51712     
    _________________________________________________________________
    leaky_re_lu_7 (LeakyReLU)    (None, 512)               0         
    _________________________________________________________________
    batch_normalization_7 (Batch (None, 512)               2048      
    _________________________________________________________________
    dense_11 (Dense)             (None, 512)               262656    
    _________________________________________________________________
    leaky_re_lu_8 (LeakyReLU)    (None, 512)               0         
    _________________________________________________________________
    batch_normalization_8 (Batch (None, 512)               2048      
    _________________________________________________________________
    dense_12 (Dense)             (None, 1)                 513       
    =================================================================
    Total params: 318,977
    Trainable params: 316,929
    Non-trainable params: 2,048
    _________________________________________________________________
    _________________________________________________________________
    Layer (type)                 Output Shape              Param #   
    =================================================================
    flatten_2 (Flatten)          (None, 784)               0         
    _________________________________________________________________
    dense_13 (Dense)             (None, 512)               401920    
    _________________________________________________________________
    leaky_re_lu_9 (LeakyReLU)    (None, 512)               0         
    _________________________________________________________________
    batch_normalization_9 (Batch (None, 512)               2048      
    _________________________________________________________________
    dense_14 (Dense)             (None, 512)               262656    
    _________________________________________________________________
    leaky_re_lu_10 (LeakyReLU)   (None, 512)               0         
    _________________________________________________________________
    batch_normalization_10 (Batc (None, 512)               2048      
    _________________________________________________________________
    dense_15 (Dense)             (None, 100)               51300     
    =================================================================
    Total params: 719,972
    Trainable params: 717,924
    Non-trainable params: 2,048
    _________________________________________________________________
    _________________________________________________________________
    Layer (type)                 Output Shape              Param #   
    =================================================================
    dense_16 (Dense)             (None, 512)               51712     
    _________________________________________________________________
    leaky_re_lu_11 (LeakyReLU)   (None, 512)               0         
    _________________________________________________________________
    batch_normalization_11 (Batc (None, 512)               2048      
    _________________________________________________________________
    dense_17 (Dense)             (None, 512)               262656    
    _________________________________________________________________
    leaky_re_lu_12 (LeakyReLU)   (None, 512)               0         
    _________________________________________________________________
    batch_normalization_12 (Batc (None, 512)               2048      
    _________________________________________________________________
    dense_18 (Dense)             (None, 784)               402192    
    _________________________________________________________________
    reshape_2 (Reshape)          (None, 28, 28, 1)         0         
    =================================================================
    Total params: 720,656
    Trainable params: 718,608
    Non-trainable params: 2,048

    aae.train(epochs=2000, batch_size=32, save_interval=200)

    ---------------------------------------------------------------------------
    InvalidArgumentError                      Traceback (most recent call last)
    <ipython-input-6-159ebfef0877> in <module>()
    ----> 1 aae.train(epochs=2000, batch_size=32, save_interval=200)

    <ipython-input-2-57f851a1818e> in train(self, epochs, batch_size, save_interval)
        113 
        114             # Generate a half batch of new images
    --> 115             latent_fake, gen_imgs = self.generator.predict(imgs)
        116 
        117             latent_real = np.random.normal(size=(half_batch, self.encoded_dim))

    /usr/local/lib/python2.7/dist-packages/Keras-2.0.8-py2.7.egg/keras/engine/training.pyc in predict(self, x, batch_size, verbose, steps)
       1715         f = self.predict_function
       1716         return self._predict_loop(f, ins, batch_size=batch_size,
    -> 1717                                   verbose=verbose, steps=steps)
       1718 
       1719     def train_on_batch(self, x, y,

    /usr/local/lib/python2.7/dist-packages/Keras-2.0.8-py2.7.egg/keras/engine/training.pyc in     _predict_loop(self, f, ins, batch_size, verbose, steps)
       1267                 else:
       1268                     ins_batch = _slice_arrays(ins, batch_ids)
    -> 1269                 batch_outs = f(ins_batch)
       1270                 if not isinstance(batch_outs, list):
       1271                     batch_outs = [batch_outs]

    /usr/local/lib/python2.7/dist-packages/Keras-2.0.8-py2.7.egg/keras/backend/tensorflow_backend.pyc in __call__(self, inputs)
       2255         updated = session.run(self.outputs + [self.updates_op],
       2256                               feed_dict=feed_dict,
    -> 2257                               **self.session_kwargs)
       2258         return updated[:len(self.outputs)]
       2259 

    /usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
        893     try:
        894       result = self._run(None, fetches, feed_dict, options_ptr,
    --> 895                          run_metadata_ptr)
        896       if run_metadata:
        897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

    /usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
       1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
       1123       results = self._do_run(handle, final_targets, final_fetches,
    -> 1124                              feed_dict_tensor, options, run_metadata)
       1125     else:
       1126       results = []

    /usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle,     target_list, fetch_list, feed_dict, options, run_metadata)
       1319     if handle is None:
       1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
    -> 1321                            options, run_metadata)
       1322     else:
       1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

    /usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
       1338         except KeyError:
       1339           pass
    -> 1340       raise type(e)(node_def, op, message)
       1341 
       1342   def _extend_graph(self):

    InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
    	 [[Node: sequential_5/flatten_2/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_5_0_1/_213, sequential_5/flatten_2/stack)]]

    Caused by op u'sequential_5/flatten_2/Reshape', defined at:
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
        app.launch_new_instance()
      File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in     launch_instance
        app.start()
      File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 477, in start
        ioloop.IOLoop.instance().start()
      File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
        super(ZMQIOLoop, self).start()
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
        self._handle_recv()
      File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
      File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
        user_expressions, allow_stdin)
      File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
        res = shell.run_cell(code, store_history=store_history, silent=silent)
      File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
        return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
        interactivity=interactivity, compiler=compiler, result=result)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in     run_ast_nodes
        if self.run_code(code, result):
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-4-3d96210dd081>", line 2, in <module>
        aae = AdversarialAutoencoder()
      File "<ipython-input-2-57f851a1818e>", line 18, in __init__
        self.generator = self.build_generator()
      File "<ipython-input-2-57f851a1818e>", line 54, in build_generator
        encoded_repr = encoder(img)
      File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 602, in __call__
        output = self.call(inputs, **kwargs)
      File "build/bdist.linux-x86_64/egg/keras/models.py", line 532, in call
        return self.model.call(inputs, mask)
      File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 2058, in call
        output_tensors, _, _ = self.run_internal_graph(inputs, masks)
      File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 2209, in run_internal_graph
        output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
      File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 484, in call
        return K.batch_flatten(inputs)
      File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 1918, in batch_flatten
        x = tf.reshape(x, tf.stack([-1, prod(shape(x)[1:])]))
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in     reshape
    name=name)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

    InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
    	 [[Node: sequential_5/flatten_2/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32,     _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_5_0_1/_213, sequential_5/flatten_2/stack)]]

​

**Comment by eriklindernoren** [comment]
Hm. What version of Keras are you using? My first guess was that this was caused by you running Python 2 but it seems to work fine for me with both Python 2 and 3.

**Comment by eriklindernoren** [comment]
Closed because of inactivity.
