### ISSUE TITLE
How to save&load CycleGan model

### ISSUE THREAD

**Issue by hirodroid** [eriklindernoren/Keras-GAN#101]
Thank you for something that will be of great help.
Let me question about preserving the model of CycleGan.
I saved & loaded as described below, is this the correct way to use the learned model?
When it was generated with the loaded model, it was not able to generate successfully.

self.g_AB.save ('./ saved_model / g_AB.h5')
self.model_AB = load_model ('./ saved_model / g_AB.h 5')
fake_B = self.model_AB.predict (org_img)

**Comment by eps696** [comment]
for further training - save with 
`self.combined.save_weights('train/%s-%d.h5' % (self.dataset_name, epoch))`
reload with 
`self.combined.load_weights('train/%s-%d.h5' % (self.dataset_name, epoch))`

to generate images - save with 
`self.g_AB.save_weights('train/%s-AB-%d.h5' % (self.dataset_name, epoch))`
`self.g_BA.save_weights('train/%s-BA-%d.h5' % (self.dataset_name, epoch))`
load with 
`self.g_AB.load_weights(a.model_name_AB)`
`self.g_BA.load_weights(a.model_name_BA)`

**Comment by himansh1314** [comment]
I saved CycleGAN model and when reloading model, I was unable to get desired results. During training, I sampled images for every epoch and was getting satisfactory results there, but the same didn't happen for loading the saved model and predicting the results. Please help.

**Comment by ashuindiana** [comment]
I ran Pix2Pix model for my dataset and got satisfactory results while sampling images during training process. I save the model weights and load it. But the loaded model produce very bad images. What to do? Please help...

**Comment by himansh1314** [comment]
The same happened with me when saving CycleGAN model.
