### ISSUE TITLE
Unable to instantiate cycgan

### ISSUE THREAD

**Issue by yashwantreddy** [eriklindernoren/Keras-GAN#102]
I have all the required package installed and yet it says - 

`ImportError                               Traceback (most recent call last)`
`<ipython-input-2-b74a358b4732> in <module>()`
`----> 1 import cyclegan`

`~\Downloads\Keras-GAN\cyclegan\cyclegan.py in <module>()`
`      3 `
`      4 from keras.datasets import mnist`
`----> 5 from keras_contrib.layers.normalization import InstanceNormalization`
`      6 from keras.layers import Input, Dense, Reshape, Flatten, Dropout, Concatenate`
`      7 from keras.layers import BatchNormalization, Activation, ZeroPadding2D`

`~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras_contrib-2.0.8`-`py3.6.egg\keras_contrib\__init__.py in <module>()`
`      2 from . import backend`
`      3 from . import datasets`
`----> 4 from . import layers`
`      5 from . import preprocessing`
`      6 from . import utils`

`~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras_contrib-2.0.8`-`py3.6.egg\keras_contrib\layers\__init__.py in <module>()`
`      1 from __future__ import absolute_import`
`      2 from .core import *`
`----> 3 from .convolutional import *`
`      4 from .pooling import *`
`      5 from .local import *`

`~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras_contrib-2.0.8`-`py3.6.egg\keras_contrib\layers\convolutional.py in <module>()`
 `    13 from keras.utils.generic_utils import get_custom_objects`
 `    14 from keras.utils.conv_utils import conv_output_length`
`---> 15 from keras.backend.common import normalize_data_format`
`     16 import numpy as np`
`     17 `

`ImportError: cannot import name 'normalize_data_format`

**Comment by tchampet** [comment]
Upgrading keras toward 2.2.4 version, deals with this problem.
