### ISSUE TITLE
WGAN.py scaling sample images

### ISSUE THREAD

**Issue by dtfoster** [eriklindernoren/Keras-GAN#103]
Should line 176 in wgan.py be:

`gen_imgs = 0.5 * (gen_imgs + 1)`

instead of:

`gen_imgs = 0.5 * gen_imgs + 1`

as gen_imgs are in the range [-1, 1] and need to be scaled to [0,1]

**Comment by DaGuT** [comment]
https://github.com/eriklindernoren/Keras-GAN/pull/118 fixed

**Comment by woctezuma** [comment]
The issue is also in [sgan.py](https://github.com/eriklindernoren/Keras-GAN/blob/1a0428a1ec441adbacf9df7cc18a6fccf75b83bc/sgan/sgan.py#L178).
