### ISSUE TITLE
Please upload saved model

### ISSUE THREAD

**Issue by tejasvx** [eriklindernoren/Keras-GAN#12]
Hi,
You  really have a great repo here. As I was looking into your repo i found out that you have folders for saved models. Can you please upload these models on google drive (if you have already trained your models). It would be really great for those who don't want to train and are only interested in results.
Thanks

**Comment by famishedrover** [comment]
@tejasvx You can train the models in less then a couple of hours tops, create a Google Cloud Account which gives you free credits to work with.

**Comment by tejasvx** [comment]
GCP free credits does not contain GPU instances but I trained the model on my laptop and it worked great.
Feel like I should close this issue anyways.

**Comment by eriklindernoren** [comment]
Some GAN implementations have a method `save_model`. This is from `acgan/acgan.py`:
```python
    def save_model(self):

        def save(model, model_name):
            model_path = "acgan/saved_model/%s.json" % model_name
            weights_path = "acgan/saved_model/%s_weights.hdf5" % model_name
            options = {"file_arch": model_path, 
                        "file_weight": weights_path}
            json_string = model.to_json()
            open(options['file_arch'], 'w').write(json_string)
            model.save_weights(options['file_weight'])

        save(self.generator, "mnist_acgan_generator")
        save(self.discriminator, "mnist_acgan_discriminator")
        save(self.combined, "mnist_acgan_adversarial")
```

I have not implemented this method for all GAN varieties, but slight modifications to this method should help you save the model you want to train.

**Comment by tejasvx** [comment]
I actually have applied this saved models function to most of your GANs implementation. My request was to upload saved hdf5 file of your implementation as training models are computationally expensive and people who are interested in results can use those models. But anyways I have implemented these models and can upload my hdf5 files if you would allow me to. 
P.S. your implementation helped me a lot in understanding GANs.

**Comment by BenjaminWegener** [comment]
#70
