### ISSUE TITLE
discogan.py can't import name InstanceNormalization

### ISSUE THREAD

**Issue by dnola** [eriklindernoren/Keras-GAN#129]
When using latest Keras (2.2.4, from pip and from github) and keras_contrib (2.0.8) running discogan.py fails with:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "discogan.py", line 5, in <module>
    from keras_contrib.layers.normalization import InstanceNormalization
ImportError: cannot import name 'InstanceNormalization'
```

I'm on Anaconda Python 3.5.6

Any help would be much appreciated!

**Comment by hasibzunair** [comment]
Use:
```
from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization
````

Refer to [#124](https://github.com/eriklindernoren/Keras-GAN/pull/124)

**Comment by dnola** [comment]
That does the trick - appreciate it!
