### ISSUE TITLE
Some questions about the label of SRGAN

### ISSUE THREAD

**Issue by xiaoxiaoze** [eriklindernoren/Keras-GAN#133]
Hello, I am the first time to contact SRGAN, When I saw SRGAN.py, I had a question, why the shape of the label is valid = np.ones((batch_size,) + self.disc_patch), finally, the label shape we got was[1,16,16,1], but we only entered an image for the discriminator network each time. This problem bothers me, I don't know what is going on here.

**Comment by eriklindernoren** [comment]
The discrimintor will output multiple values (shaped `(16, 16, 1)`) indicating whether it sees each of these 16 patches as real or fake. Since you have one image the total shape will be `(1, 16, 16, 1)`.
