### ISSUE TITLE
Discriminator sigmoid activation?

### ISSUE THREAD

**Issue by Ouwen** [eriklindernoren/Keras-GAN#138]
https://github.com/eriklindernoren/Keras-GAN/blob/b817bb68993e21cdcf4581798b371b29dd0d90f2/cyclegan/cyclegan.py#L140-L159

I was wondering if there should be a sigmoid activation on the validity convolution.

**Comment by eriklindernoren** [comment]
I'm using a least squares adversarial objective, and therefore the discriminators have a linear activation on the output layer. You can find more information about this in the LSGAN paper https://arxiv.org/abs/1611.04076.

**Comment by Ouwen** [comment]
Interesting paper, thanks for sharing!
