### ISSUE TITLE
A TypeError when run SRGAN

### ISSUE THREAD

**Issue by DCSong** [eriklindernoren/Keras-GAN#144]
Hello, thanks for your great work. I'm new to SRGAN. When I try to run srgan.py, there is a TypeError: __init__() got an unexpected keyword argument 'dataset_name' (line: 58). How can I solve it? Thank you.

`
# Configure data loader
        self.dataset_name = 'img_align_celeba'
        self.data_loader = DataLoader(dataset_name=self.dataset_name,
                                      img_res=(self.hr_height, self.hr_width))
`

**Comment by eriklindernoren** [comment]
That's strange. As you can see in `Dataloader.__init__` it takes a keyword argument `dataset_name`. Could you perhaps pull the latest version and try again?

**Comment by DCSong** [comment]
> That's strange. As you can see in [`Dataloader.__init__`](https://github.com/eriklindernoren/Keras-GAN/blob/master/srgan/data_loader.py) it takes a keyword argument `dataset_name`. Could you perhaps pull the latest version and try again?


Sorry, I have found my fault. I referenced a wrong Dataloader. Thanks for your reply.
