### ISSUE TITLE
Interpreting critic and generator loss in wgan-gp

### ISSUE THREAD

**Issue by jamesTait-jt** [eriklindernoren/Keras-GAN#145]
I've reimplemented wgan-gp using this code as a skeleton and attempted to apply it to denoising monte carlo rendered images using a perceptual loss component as well. the images look okay, but nowhere near the quality of the images using _just_ the generator network with perceptual loss. I've attached an image of my negative critic loss because I don't think it's right and I'm baffled as to how I might be able to fix it.

My code is here:
https://github.com/jamesTait-jt/monte-carlo-raytracer/blob/master/denoiser/code/gan.py

Look for the trainWGAN function.

If anyone could help I'd be grateful! thanks!

![image](https://user-images.githubusercontent.com/22934203/56100237-a5a46380-5f05-11e9-89e6-2056d4d0fbcb.png)

![image](https://user-images.githubusercontent.com/22934203/56100244-bd7be780-5f05-11e9-865a-7484abcd1a73.png)

Here's a test image after 80 generator updates (5 critic updates per generator)

![image](https://user-images.githubusercontent.com/22934203/56100268-24010580-5f06-11e9-85c7-b838f7448ac5.png)

**Comment by lennert130994** [comment]
Did you manage to solve this?
