### ISSUE TITLE
Module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by cestlaviebai** [eriklindernoren/Keras-GAN#18]
Hi Erik,

Have you ever met with the error "module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'"?
This is probably because my tensorflow backend is in an older version 1.0.0. But it looks like I can only update the tensorflow outside keras, instead of update the "tensorflow backend" within keras.
Do you have a clue? THANKS!

Di

**Comment by eriklindernoren** [comment]
No, sorry I have not had this problem before. You could try and use relu instead of leaky relu and see if that helps you get the script running at least.

**Comment by cestlaviebai** [comment]
Thanks. For some reason, it works well on GPU, but not on CPU. Anyway, it runs.
