### ISSUE TITLE
SeqGAN?

### ISSUE THREAD

**Issue by cbsudux** [eriklindernoren/Keras-GAN#19]
Hi, good work mate. Are you planning on adding SeqGAN? 

Paper : [https://arxiv.org/abs/1609.05473](url)
TF code : [https://github.com/LantaoYu/SeqGAN](url)

**Comment by eriklindernoren** [comment]
Thanks! No plans as of now. I'm currently doing some work on domain adaptation using GANs so I might add a GAN for DA soon. Feel free to give it a go if you want. Pull requests are very welcomed!

**Comment by cbsudux** [comment]
Alright, I'll give it a go!
