### ISSUE TITLE
SRGAN: Saving and reloading the model

### ISSUE THREAD

**Issue by kaushal1989** [eriklindernoren/Keras-GAN#195]
Hi,

Thanks for the SRGAN implementation. 

I am trying to save the trained SRGAN model, say at every 500th epoch and use it to generate the high-resolution images on a different set. How this can be achieved?

I have added a few lines in the existing code to save the model:

```      
           # If at save interval => save generated image samples and model
            if epoch % sample_interval == 0:
                self.sample_images(epoch)

                # Save the model
                filename = 'model_%04d.h5' % (epoch+1)
                self.generator.save(filename)
```

And to load it, I do the following:

```
from keras.models import load_model
srgan = SRGAN()
srgan.model = load_model('model_0500.h5')
fake_img = srgan.generator.predict(input_img)
```
Is it correct?

Thanks.

**Comment by awalker0215** [comment]
at load model part ,i think should use the following:

`a = load_model('model_0500.h5')

#input_img have to rescale
fake_img = a.predict(input_img)`

**Comment by kaushal1989** [comment]
@awalker0215 Thanks, this works.
