### ISSUE TITLE
cGAN with multi-class labels

### ISSUE THREAD

**Issue by jrthom18** [eriklindernoren/Keras-GAN#20]
Thank you for the great work here it's helped me jump start my own project!  Would it be possible to adapt the cGAN generator and discriminator networks to handle label inputs of shape `(x,)` where `x` is a positive integer greater than 1?  This way the label could be an array of values (i.e. in a case where `x=4` the label could look something like `[1, 0, 1, 1]`) allowing the cGAN to be trained for more complex classification tasks.

**Comment by eriklindernoren** [comment]
Sure, in the current implementation of cGAN the generator and discriminator expects a label input of shape `(x,)`, where `x` is a integer value between 0 and `self.num_classes` - 1. So for MNIST this integer value will be between 0 and 9. But this can be adapted to any classification task.

**Comment by jrthom18** [comment]
The problem is label shape is hardcoded as `label = Input(shape=(1,), dtype='int32')` so trying to use any shape greater than 1 will cause an error during the `model_input = multiply([noise, label_embedding])` operation.  The error will be something like `ValueError: Operands could not be broadcast together with shapes (x,) (y,)`

**Comment by eriklindernoren** [comment]
Oh, I see what you mean. Hm. I haven't tried this but I think you can do:

```python
        noise = Input(shape=(self.latent_dim,))
        label = Input(shape=(self.label_dim,), dtype='int32')

        label_embedding = Embedding(self.num_classes, self.latent_dim, input_length=self.label_dim)(label) # shape (batch_size, self.label_dim, self.latent_dim)

        model_input = multiply([noise, label_embedding]) # shape (batch_size, self.label_dim, self.latent_dim)
        model_input = Flatten()(model_input) # shape (batch_size, self.latent_dim * self.label_dim)
```
Then you would have to set `model.add(Dense(256, input_dim=self.latent_dim))` to `model.add(Dense(256, input_dim=self.latent_dim * self.label_dim))` on line 60.

**Comment by jrthom18** [comment]
Ah yes that appears to work. Then for the discriminator network it's the same code just swap `self.latent_dim` with `np.prod(self.img_shape)` and rework the training loop as necessary and it's good to go.

**Comment by mrgloom** [comment]
Is it common to use `Embedding` for CGAN? why not just append label to flattened image?

Related:
https://github.com/eriklindernoren/Keras-GAN/issues/143
