### ISSUE TITLE
No display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by nobodykid** [eriklindernoren/Keras-GAN#23]
Hello I'm trying to run GAN script in `gan\gan.py`, but I'm getting an error that said 

`_tkinter.TclError: no display name and no $DISPLAY environment variable`

and here's the screenshot
![image](https://user-images.githubusercontent.com/12664445/38602425-e1d3db8a-3d94-11e8-8e90-6fd00787207e.png)

Is there any solution for this?

**Comment by CreeperGo** [comment]
How did you run it?You can't run it by a ssh interface(or tty,etc.),because the $DISPLAY environment variable has not been set.Try running it after startx or on graphical termial(like lxterm).
(I'm sorry for my bad English because it isn't my native language :D)

**Comment by nobodykid** [comment]
I see, thank you very much for your solution. It worked now
