### ISSUE TITLE
when training CGAN, raise AttributeError: 'list' object has no attribute 'keys'  in the following code

### ISSUE THREAD

**Issue by louiseviden** [eriklindernoren/Keras-GAN#245]
`d_loss_real = self.discriminator.train_on_batch(imgs, [valid, one_hot_labels], class_weight=[cw1, cw2])`
` d_loss_fake = self.discriminator.train_on_batch(gen_imgs, [fake, fake_labels], class_weight=[cw1, cw2])`

**Comment by yyz277322264** [comment]
Has the problem been solved？

**Comment by louiseviden** [comment]
> Has the problem been solved？

no

**Comment by GaNir** [comment]
The problem is related to class_weight=[cw1, cw2] parameter

**Comment by RahaSoleymanzadeh** [comment]
> The problem is related to class_weight=[cw1, cw2] parameter

How can I solve the same problem?

**Comment by anwarsaqib** [comment]
Did you solve the problem? I am facing the issue with SGAN
