### ISSUE TITLE
Ideas on CGAN code

### ISSUE THREAD

**Issue by miranthajayatilake** [eriklindernoren/Keras-GAN#25]
Hi Erik! Great work with the repo.

I was following the CGAN code along with the paper and I did some alterations to try and match the models to exactly what the paper says. I knew the models presented in the paper would be less productive than your code but just wanted to replicate those and see. For example the generator model in the paper mentions this:

> In the generator net, a noise prior z with dimensionality 100 was drawn from a uniform distribution
> within the unit hypercube. Both z and y are mapped to hidden layers with Rectified Linear Unit
> (ReLu) activation [4, 11], with layer sizes 200 and 1000 respectively, before both being mapped to
> second, combined hidden ReLu layer of dimensionality 1200. We then have a final sigmoid unit
> layer as our output for generating the 784-dimensional MNIST samples.    

So with this I altered the code like this:
```
def build_generator(self):

       model = Sequential()

        model.add(Dense(200, input_dim=self.latent_dim))
        model.add(Activation('relu'))
        model.add(BatchNormalization(momentum=0.8))

        model.add(Dense(1000))
        model.add(Activation('relu'))
        model.add(BatchNormalization(momentum=0.8))

        model.add(Dense(1200, input_dim=self.latent_dim))
        model.add(Activation('relu'))
        model.add(BatchNormalization(momentum=0.8))

        model.add(Dropout(0.5))

        model.add(Dense(np.prod(self.img_shape), activation='sigmoid'))
        model.add(Reshape(self.img_shape))


        model.summary()

        noise = Input(shape=(self.latent_dim,))
        label = Input(shape=(1,), dtype='int32')
        label_embedding = Flatten()(Embedding(self.num_classes, self.latent_dim)(label))

        model_input = multiply([noise, label_embedding])

        img = model(model_input)
        

        return Model([noise, label], img)

```
But still I think this not exactly what the paper means. What I understand from the paper is the noise and labels are first fed into two different layers and then combined to one layer. 

Does this mean that there should be three separate models inside the generator? Or am I mistaken thinking that? Would like to hear your thoughts. 

Thanks!

**Comment by eriklindernoren** [comment]
Yeah, the implementations will in some cases not exactly mirror the ones described in the papers. Here is how I interpret the architecture described in the text you posted:

```python
def build_generator(self):

  # Noise layer
  noise = Input(shape=(self.latent_dim,))
  noise_emb = Dense(200, activation='relu')(noise)                # out_shape: (batch_size, 200)

  # Label layer
  label = Input(shape=(self.num_classes+1,))
  label_emb = Dense(1000, activation='relu')(label)               # out_shape: (batch_size, 1000)

  # Merge layer
  noise_label_merged = Concatenate()([noise_emb, label_emb])      # out_shape: (batch_size, 1200)
  img_flat = Dense(np.prod(self.img_shape), activation='sigmoid') # out_shape: (batch_size, 784)
  img = Reshape(self.img_shape)(img_flat)                         # out_shape: (batch_size, 28, 28, 1)


  return Model([noise, label], img)
```

**Comment by miranthajayatilake** [comment]
Thanks a lot for this Erik! Exactly what I wanted to figure out! Keep up the great work.

**Comment by andrearama** [comment]
Might I ask what exactly the main change is supposed to do, and the motivation of such choice? 
I mean the line:
`Flatten()(Embedding(self.num_classes, self.latent_dim)(label))`

Thanks

**Comment by OUARED-A** [comment]
Thanks a lot for this Erik!
