### ISSUE TITLE
a question about gcgan network

### ISSUE THREAD

**Issue by 0AlvinLO0** [eriklindernoren/Keras-GAN#3]
hello,Erik, thanks for your sharing of these kinds of GAN, and I wonder if my data is 3 channel color images like cifar, how to apply it, for if I just change the size and channel it arise an error 'number of input channels does not match corresponding dimension of filter, 1 != 3'

**Comment by eriklindernoren** [comment]
Hi, thanks! I'm assuming you're referring to DCGAN? If so hopefully all you need to do is change:
`model.add(Conv2D(1, kernel_size=3, padding="same"))` 
to 
`model.add(Conv2D(self.channels, kernel_size=3, padding="same"))`

**Comment by 0AlvinLO0** [comment]
oh yeah dcgan, yes the network works, thanks a lot for your help~~

**Comment by flyfj** [comment]
the input dimension for cifar (32) is different from mnist (28), how can it be changed to generate that size?

**Comment by eriklindernoren** [comment]
Change 
`self.img_rows = 28`
`self.img_cols = 28` 
`self.channels = 1` 
to
`self.img_rows = 32`
`self.img_rows = 32`
`self.channels = 3` 
and also make the changes I suggested in my answer above.

**Comment by flyfj** [comment]
thanks for the reply.
i think i also need to modify 'model.add(Dense(128 * 8 * 8))' to make the generator produce 32x32 image, otherwise it produces 28x28. is that expected?

**Comment by eriklindernoren** [comment]
Yeah, that is correct. Change these lines:
`model.add(Dense(128 * 7 * 7, activation="relu", input_shape=noise_shape))`
`model.add(Reshape((7, 7, 128)))`
to
`model.add(Dense(128 * 8 * 8, activation="relu", input_shape=noise_shape))`
`model.add(Reshape((8, 8, 128)))`

**Comment by flyfj** [comment]
is there a formula to calculate the layer dimension given an arbitrary input image size? what reference/paper do you use to implement the network?

**Comment by eriklindernoren** [comment]
A suggestion I often see is to start with a shallow network, get something that works and then expand on that. There is no recipe when it comes to building the network's architecture that guarantees good results though, and it's extra tricky when it comes to GANs, because of a number of factors. For this example I build the network based of the architecture in the paper and some experimentation. I can recommend this page: https://github.com/soumith/ganhacks (from one of the authors of DCGAN).

**Comment by flyfj** [comment]
thanks for the guide, very helpful. agree on starting with shallow ones that could fit the data first.
excellent work on the implementation!
