### ISSUE TITLE
Real and fake reversed in AAE

### ISSUE THREAD

**Issue by plaut** [eriklindernoren/Keras-GAN#34]
In the adversarial autoencoder, lines 139 and 141 are:
`latent_fake = self.encoder.predict(imgs)`
`latent_real = np.random.normal(size=(half_batch, self.encoded_dim))`
Shouldn't this be reversed?

**Comment by eriklindernoren** [comment]
Since the encoder want to find an embedding of the data that mirrors a normal distribution; samples from a normal distribution are used as real examples for the discriminator and encoded images are used a false examples.
