### ISSUE TITLE
SRGAN subpixel 

### ISSUE THREAD

**Issue by caiya55** [eriklindernoren/Keras-GAN#42]
Hi : 
Thanks very much for your comprehensive  networks from gan. I am learning the SRGAN and I found that in the original paper the sub-pixel layers are used in the generator. But in your code, the deconvolution layers are upsampling+ conv2D. I'd like to know what is the difference,  do the result keeps the same?

**Comment by eriklindernoren** [comment]
Hi,
The reason I use upsampling + conv instead of fractionally strided convolutions is that the latter results in checkerboard artifacts if you're not careful about setting the filter size and stride. See https://distill.pub/2016/deconv-checkerboard/ for more details about this.

**Comment by BenjaminWegener** [comment]
https://gist.github.com/BenjaminWegener/1205c1059acb72be75179597349e969b subpixelconv keras only
