### ISSUE TITLE
CycleGan

### ISSUE THREAD

**Issue by parasjain-12** [eriklindernoren/Keras-GAN#47]
When I running your code for Cycle-Gan for some dataset it's working good like cityscapes,apple2orange
but for some it's showing the following error .Please help me to resolve .
And what can change in your code to see the result in Google Colob since don't have GPU

`Traceback (most recent call last):
  File "cyclegan.py", line 258, in <module>
    gan.train(epochs=200, batch_size=1, sample_interval=200)
  File "cyclegan.py", line 170, in train
    for batch_i, (imgs_A, imgs_B) in enumerate(self.data_loader.load_batch(batch_size)):
  File "/content/project1211/CycleGan/project3/project344/Keras-GAN/cyclegan/data_loader.py", line 42, in load_batch
    path_A = np.random.choice(path_A, total_samples, replace=False)
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty`

**Comment by ubersexualShupeng** [comment]
In the cycle-gan keras code, why the 'combine model' required using the 'identity mapping' as a loss (as following): 
# Identity mapping of images
img_A_id = self.g_BA(img_A)
img_B_id = self.g_AB(img_B)

Anyone have idea? In the original paper (Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks), they do not have this terms in their loss. Am I correct?

**Comment by eriklindernoren** [comment]
@parasjain-12 The dataloader can't find images in the path that you specified in that case. So `np.random.random([])` will throw an errow.

@ubersexualShupeng The identity loss in from CycleGAN means that an image from domain A that is translated to domain A should exactly 
match the original image. In this case images from A translated to domain A and images from domain B 
translated to domain B should reproduce the original images, just as the implementation does. It is used in the paper for painting-to-photograph translation problems.

**Comment by ubersexualShupeng** [comment]
@eriklindernoren Thank you for your kind response! I understand that the 'reconstruct image' should be matched to the 'real image', as the following two lines code:

Translate images back to original domain
reconstr_A = self.g_BA(fake_B)
reconstr_B = self.g_AB(fake_A)

However, I quite confuse with another two line codes as follows:
Identity mapping of images
 img_A_id = self.g_BA(img_A)
 img_B_id = self.g_AB(img_B)

Why the model loss required both of them? 
Thanks.

**Comment by eriklindernoren** [comment]
@ubersexualShupeng This is explained in detail in the section _Photo generation from paintings_ in the paper (https://arxiv.org/pdf/1703.10593.pdf).

**Comment by ubersexualShupeng** [comment]
@eriklindernoren OK. Got it. Thank you!

**Comment by Rabia-Raja** [comment]
I run this code and obtained good results on different datasets but I want to know something 
about quantitative parameters we obtained after the end of code. 

Acc, adv: recon, and iD? Can you please explain them

**Comment by DanielXu123** [comment]
Hi, erik.

May I ask how to save the trained model of cyclegan?

I tried follow the codes of acgan.py but still failed to save the generate model and the discrimitor model for now.
