### ISSUE TITLE
Is it possible to include callbacks (tensorboard) to GANs?

### ISSUE THREAD

**Issue by LiangqunLu** [eriklindernoren/Keras-GAN#52]
I am trying the DCGAN for my project. I am wondering if there is any way callbacks can be included in the Keras model.train_on_batch so that I can trace G-loss and D-loss in the tensorboard?

**Comment by GerrieCrafford** [comment]
Since you are already in control of the training loop, you can directly log the required values for tensorboard as shown in this [gist](https://gist.github.com/joelthchao/ef6caa586b647c3c032a4f84d52e3a11)

The relevant parts are summarized below.

**Define the logging function**

```
def write_log(callback, names, logs, batch_no):
    for name, value in zip(names, logs):
        summary = tf.Summary()
        summary_value = summary.value.add()
        summary_value.simple_value = value
        summary_value.tag = name
        callback.writer.add_summary(summary, batch_no)
        callback.writer.flush()
```

**Setup the callback**

```
log_path = './logs'
callback = TensorBoard(log_path)
callback.set_model(model)
```

**Call the log function after training**

```
d_loss = discriminator.train_on_batch...
g_loss = combined.train_on_batch...

write_log(callback, ['g_loss'], [g_loss], batch_no)
write_log(callback, ['d_loss'], [d_loss], batch_no)
```

**Comment by ShuvenduBikash** [comment]
Got this error
g_loss is adding properly but causing problem with d_loss


```
            d_loss_real = self.discriminator.train_on_batch(imgs, np.ones((half_batch, 1)))
            d_loss_fake = self.discriminator.train_on_batch(gen_imgs, np.zeros((half_batch, 1)))
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)
```

```
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Research/Generative_adversarial_networks/dcgan/keras_degan.py", line 196, in <module>
    dcgan.train(callback, epochs=4000, batch_size=32, save_interval=200)
  File "D:/Research/Generative_adversarial_networks/dcgan/keras_degan.py", line 163, in train
    write_log(callback, ['d_loss'], [d_loss], epoch)
  File "D:/Research/Generative_adversarial_networks/dcgan/keras_degan.py", line 22, in write_log
    summary_value.simple_value = value
  File "C:\Users\bikas\Anaconda3\lib\site-packages\numpy\core\arrayprint.py", line 1379, in array_repr
    if type(arr) is not ndarray:
SystemError: <class 'type'> returned a result with an error set
```

**Comment by GerrieCrafford** [comment]
@ShuvenduBikash from the error message it seems that the loss contains multiple values (did you specify metrics in the model.compile function?).

You can change the call to the log function to `write_log(callback, ['d_loss'], [d_loss[0]], batch_no)` if you only want to log the loss.

You should also be able to log the loss and other metrics by changing it to `write_log(callback, ['d_loss', 'other_metric_name', ...], d_loss, batch_no)`

**Comment by ShuvenduBikash** [comment]
@GerrieCrafford Thanks. I got the problem

Could you please give me some reference to learn details about this in details. I don't quite like the tensorflow's own website.

**Comment by GerrieCrafford** [comment]
@ShuvenduBikash Glad I could help.

Unfortunately, I don't know of a reference other than TensorFlow's website (or maybe Keras' website).
