### ISSUE TITLE
Bidirectional GAN seems incomplete

### ISSUE THREAD

**Issue by mfarahmand98** [eriklindernoren/Keras-GAN#58]
Searching in Google for some Keras implementation for Bidirectional GAN led me here and I copied your code. But there seems to be a problem; the code never trains the encoder network! How is it supposed to learn the distribution?
Then I thought that there might be some underlying codes training it, so I tweaked the 'train' method so it would return the generator and the encoder models so I could check if the encoder has been trained. I tried to run the below code, which is part of the training loop:
```
    # Sample noise and generate img
    z = np.random.normal(size=(batch_size, self.latent_dim))
    imgs_ = self.generator.predict(z)
    # Select a random batch of images and encode
    idx = np.random.randint(0, X_train.shape[0], batch_size)
    imgs = X_train[idx]
    z_ = self.encoder.predict(imgs)
```
But then this happend:
```
ValueError: Error when checking input: expected input_4 to have 4 dimensions, but got array with shape (32, 28, 28)
```
I honestly don't know what's wrong! If this code worked fine in the loop why isn't it working outside of it? I did load the mnist dataset. And I still don't know if the encoder gets trained...

**Comment by ShuvenduBikash** [comment]
add the channel dimension. Input shape should be (32, 3, 28, 28). If you are using something like mnist dataset with one channel reshape it to (32, 1, 28, 28). You might need to change the channel size in code

**Comment by mfarahmand98** [comment]
Thanks!
But about the encoder, do you know if it's being trained somehow or the code is just incomplete? Because it's just defined and never trained!

**Comment by ShuvenduBikash** [comment]
Yes, it is. The train function does that job

**Comment by mfarahmand98** [comment]
The only method it invokes on the encoder model is predict! I thought that just passed some input through the network. If you could tell me which portion of the code trains the encoder that would be so kind of you... I'm kinda lost!

**Comment by ShuvenduBikash** [comment]
find the `train_on_batch()` method inside the code

**Comment by mfarahmand98** [comment]
No such method was ever invoked on the encoder modol!

**Comment by mfarahmand98** [comment]
I found it! For anyone who might have the same question, the encoder and the generator are trained together as `bigan_generator`.
