### ISSUE TITLE
CC GAN

### ISSUE THREAD

**Issue by sigmoidx** [eriklindernoren/Keras-GAN#6]
Hello?

I've been running the CC GAN code and the terminal output looks quite strange.
Is it normal for CC GAN?

**409 [D loss: nan, acc: 50.00%, op_acc: 26.56%] [G loss: nan, mse: nan]
410 [D loss: nan, acc: 50.00%, op_acc: 21.88%] [G loss: nan, mse: nan]
411 [D loss: nan, acc: 50.00%, op_acc: 29.69%] [G loss: nan, mse: nan]
412 [D loss: nan, acc: 50.00%, op_acc: 21.88%] [G loss: nan, mse: nan]
413 [D loss: nan, acc: 50.00%, op_acc: 23.44%] [G loss: nan, mse: nan]
414 [D loss: nan, acc: 50.00%, op_acc: 28.12%] [G loss: nan, mse: nan]
415 [D loss: nan, acc: 50.00%, op_acc: 31.25%] [G loss: nan, mse: nan]
416 [D loss: nan, acc: 50.00%, op_acc: 20.31%] [G loss: nan, mse: nan]**

**Comment by eriklindernoren** [comment]
Hi,

I think this you're having the same issue as #2 .
Try to either add 'from __future__ import division' or run do 'git pull'. This is
fixed in 5fa690b.

Regards,
Erik
