### ISSUE TITLE
SRGAN Dataset cannot be download

### ISSUE THREAD

**Issue by daifeng2016** [eriklindernoren/Keras-GAN#65]
when I download the dataset using the URL provided in SRGAN.py file, the Internet denotes "This link is temporarily disabled. The person who shared it hit their daily limit of traffic or downloads. Learn about traffic limits."  How to solve this problem?

**Comment by kelmok** [comment]
I have encountered the same issue -- has this been resolved? can this be shared through another server?

**Comment by kelmok** [comment]
The original dataset appears to be available here:

[http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html)
[https://drive.google.com/open?id=0B7EVK8r0v71pZjFTYXZWM3FlRnM](https://drive.google.com/open?id=0B7EVK8r0v71pZjFTYXZWM3FlRnM)

**Comment by hasibzunair** [comment]
Also [here](https://www.kaggle.com/jessicali9530/celeba-dataset).
