### ISSUE TITLE
44         path = glob.glob('./datasets/%s/%s/*' % (self.dataset_name, data_type)):      45       46   TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by nandyadav** [eriklindernoren/Keras-GAN#72]
44         path = glob.glob('./datasets/%s/%s/*' % (self.dataset_name, data_type)):
     45 
     46 

TypeError: 'module' object is not callable

**Comment by eriklindernoren** [comment]
What model are you trying to run?

**Comment by eriklindernoren** [comment]
Maybe you're trying to run an old version. This is how the current version of `srgan/data_loader.py` looks like: 
```python
        path = glob('./datasets/%s/*' % (self.dataset_name))
```

Can you try updating?
