### ISSUE TITLE
[question]: Can I use your codes for any image size ?

### ISSUE THREAD

**Issue by thusinh1969** [eriklindernoren/Keras-GAN#8]
Hi,

Great stuffs really on the new and difficult subject likes GAN. I have been scratching my head going through loads of documentations, codes and test myself, still a bit blur :( ...

One question before I start play around with your codes was that if your code works with **ANY image size** ?

Thanks,
Thu Sinh

**Comment by eriklindernoren** [comment]
Sure, just change `self.img_rows` and `self.img_cols` in the implementations and it should work.
