### ISSUE TITLE
Doubts in compiling discriminator for the combined model

### ISSUE THREAD

**Issue by zohairshafi** [eriklindernoren/Keras-GAN#91]
Hello! 

I noticed that for the combined model, you compile the discriminator, then set trainable to false. Doing this gives a warning as follows : 
```
UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
```

But, this works well. Generated images are nice within a few iterations. 

However, if I set the discriminator to compile after setting trainable to false, the warning goes away but the generator generates only noise. 

I can't understand why this happens. Would you happen to know why? 

Love the entire repo by the way. Its incredible! 

Thank you!

**Comment by kjaquier** [comment]
See https://github.com/keras-team/keras/issues/8585#issuecomment-428815858

**Comment by zohairshafi** [comment]
Aaah thank you!
