### ISSUE TITLE
SRGAN with Grayscale images

### ISSUE THREAD

**Issue by AbdullahMohamed55** [eriklindernoren/Keras-GAN#94]
When use self.channels =1 i get an error that vgg was expecting number of inputs =3 not 1 does any one knows the solution ?

**Comment by andronovhopf** [comment]
I don't know an easy way to reconfigure the VGG layers to take only 1 channel input, but I am training SRGAN on grayscale images by feeding in images in grayscale with 3 identical channels. You can do this in the data_loader.py file by making two modifications:

First, be sure you are reading your training files in in 1-channel mode, so change the image reading function:
```
def imread(self, path):
        return imread(path, mode='L').astype(np.float)
```
Then, grow the np array to three channels by duplicating the first channel:

`img = np.repeat(img[:, :, np.newaxis], 3, axis=2)`

Hope this helps!

**Comment by hasibzunair** [comment]
You can stack the single channel to make it rank 3. I did the same for training MNIST on VGG which accepts 3 channels. Refer to [#11208](https://github.com/keras-team/keras/issues/11208).

Hope this helps.
