### ISSUE TITLE
Looks like no dropout can  be used in the generator.

### ISSUE THREAD

**Issue by geekbutton** [eriklindernoren/Keras-GAN#96]
As I think, there can be no dropout in the generator while the neurons will be dropped randomly, so that the results for the generator.predict(noise) and  self.combined.train_on_batch(noise, valid) will be different. I want to know is that right to use dropout layers in the generator?

**Comment by eriklindernoren** [comment]
Yes, you could use dropout in the generator. This would essentially force the generator to produce convincing samples even without some neurons. Samples being different is not an issue as the purpose of the generator is to produce different samples as long as they are deemed to have been sampled from the same data generation distribution as your dataset. This is more of a general question about GANs though and not directly related to this repo. Good luck!
